In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)


2.3.0


Introduction to tensors

creating tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()


7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
Tensor = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

In [13]:
Tensor.ndim


3

In [14]:
Tensor.shape

torch.Size([1, 3, 3])

In [15]:
Tensor[0][0][2]

tensor(3)

In [16]:
###RANDOM TENSOR

In [17]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8142, 0.6633, 0.8749, 0.3608],
        [0.9886, 0.2061, 0.6911, 0.1051],
        [0.8388, 0.5000, 0.6079, 0.4483]])

In [18]:
random_image_size_tensor =torch.rand(size=(224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros = torch.zeros(3,4)


In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
torch.zeros_like(torch.arange(start = 1 , end =11 , step =1))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
float_tensor = torch.tensor([3.0 ,6.0 ,9.0], dtype=None , device='cpu' , requires_grad = False)
float_tensor

tensor([3., 6., 9.])

In [23]:
float_tensor.dtype

torch.float32

In [24]:
some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.3373, 0.0659, 0.6734, 0.4255],
        [0.6103, 0.0597, 0.5746, 0.5414],
        [0.0631, 0.1457, 0.3302, 0.5621]])

In [25]:
print(some_tensor)
print(f"Data type: {some_tensor.dtype}")
print(f"Shape: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3373, 0.0659, 0.6734, 0.4255],
        [0.6103, 0.0597, 0.5746, 0.5414],
        [0.0631, 0.1457, 0.3302, 0.5621]])
Data type: torch.float32
Shape: torch.Size([3, 4])
Device tensor is on: cpu


In [26]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
tensor * 10

tensor([10, 20, 30])

In [28]:
tensor - 10

tensor([-9, -8, -7])

In [29]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [30]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [31]:
tensor * tensor

tensor([1, 4, 9])

In [32]:
torch.matmul(tensor,tensor)

tensor(14)

In [33]:
%%time
value = 0 
for i in range(len(tensor)):
    value+= tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 31.2 ms
Wall time: 1.01 ms


In [34]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [35]:
tensor @ tensor

tensor(14)

In [36]:
tensor.size()

torch.Size([3])

In [37]:

x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [38]:
x_reshaped = x.reshape(1,9)
x_reshaped ,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [39]:
z=x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [40]:
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [41]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
x_s=torch.tensor([[1,2,2,1,2,3,1,2]])
x_s ,x_s.shape


(tensor([[1, 2, 2, 1, 2, 3, 1, 2]]), torch.Size([1, 8]))

In [43]:
x_squeezed = torch.squeeze(x_s,dim=0)
x_squeezed , x_squeezed.shape

(tensor([1, 2, 2, 1, 2, 3, 1, 2]), torch.Size([8]))

In [44]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed , x_unsqueezed.shape

(tensor([[1, 2, 2, 1, 2, 3, 1, 2]]), torch.Size([1, 8]))

In [45]:
x_original = torch.rand(size=(244,244,3))


In [46]:
x_permuted = x_original.permute(2,0,1)
print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


In [47]:
x_original[0,0,0] = 1236

In [48]:
x_permuted[0,0,0]

tensor(1236.)

In [49]:
##
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
x[0][1][1]

tensor(5)

In [51]:
x[:,1,1]

tensor([5])

In [52]:
array = np.arange(1,8)
tensor = torch.from_numpy(array)
array , tensor

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [53]:
array = array+ 1
array , tensor

(array([2, 3, 4, 5, 6, 7, 8]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [54]:
random_A = torch.rand(3,4)
random_B = torch.rand(3,4)
print(random_A == random_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [55]:
random_seed = 42
torch.manual_seed(random_seed)
random_C = torch.rand(3,4)
torch.manual_seed(random_seed)
random_D = torch.rand(3,4)
random_C , random_D
print(random_C== random_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
